### ISSUE TITLE
R820T2 Register descriptions

### ISSUE THREAD

**Issue by erlendse** [old-dab/rtlsdr#1]
The last register descriptions you have imported refers to a RT810P2 tuner, that is clearly similar but I know no details about.

Just be aware some stuff is likely wrong, and a lot seems correct.

Also, the VCO ADC/DAC most likely isn't so.

It's more likely to be VCO band selected (you have VCO ADC), and VCO band force(you have VCO DAC)

**Comment by old-dab** [comment]
Done.
