### ISSUE TITLE
rtl_tcp output level in manual gain mode

### ISSUE THREAD

**Issue by KejPi** [old-dab/rtlsdr#10]
When I switch to manual gain mode for rtl_tcp, the expected output level should increase as the gain increases until it reached saturation nearly to 127. I can see instead that the level estimated by AbracaDABra is around 85 for wide range of gain values and then it even decreases for extreme gain level. It looks like some kind of AGC running in server. It is thus not possible to implement reasonable AGC in client with target level > 85. Is it intended behaviour? 

Note: When I use the driver directly, everything works as expected.

**Comment by old-dab** [comment]
That's the digital AGC of the RTL2832 chip.
Switch it off, if you wish manual gain mode.
Switch it on, if you wish tuner AGC.

**Comment by KejPi** [comment]
Thanks, it works, closing the issue.
