### ISSUE TITLE
Library identification

### ISSUE THREAD

**Issue by KejPi** [old-dab/rtlsdr#8]
Hi,
It would be great if library identifies itself during compile time or during cmake. The API is extended wrt. original rtl-sdr implementation thus it makes sense to distinguish library implementation on client side. 

Currently I use `#ifdef SI2168_CHIP_ID` to recognise this version but it is rather stupid workaround. I know that the original API is working as before but I would like to use extended API if it is available. 

Something like this in rtl-sdr.h would help :-)

#define RTL_SDR_OLD_DAB 1

Thanks!

**Comment by old-dab** [comment]
I'm thinking about it.
You can also use rtlsdr_set_tuner_bandwidth() with this library, no distinction necessary.
rtlsdr_set_and_get_tuner_bandwidth() is from here: https://github.com/librtlsdr/librtlsdr/

**Comment by KejPi** [comment]
Yes, I know I can use it, but knowing the real bandwidth is an interesting feature. It would be just nice if the library identifies itself, also version information should be included in header in my opinion.

**Comment by old-dab** [comment]
All done.
